### ISSUE TITLE
Plugin does not work properly after latest tradfri gateway firmaware update

### ISSUE THREAD

**Issue by radzio** [treban/pimatic-tradfri#14]
```
error [pimatic]: A uncaught exception occurred: SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at OutgoingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/tradfri-coapdtls.js:320:37)
    at emitOne (events.js:101:20)
    at OutgoingMessage.emit (events.js:188:7)
    at Agent.handle [as _handle] (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:326:7)
    at DtlsClientSocket.socket.on.err (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:95:14)
    at emitOne (events.js:96:13)
    at DtlsClientSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at DtlsClientSocket.Readable.push (_stream_readable.js:130:10)
    at DtlsClientSocket._onMessage (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:89:12)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:540:8)
 This is most probably a bug in pimatic or in a module, please report it!
07:56:56error [pimatic]: A uncaught exception occurred: SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at OutgoingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/tradfri-coapdtls.js:320:37)
    at emitOne (events.js:101:20)
    at OutgoingMessage.emit (events.js:188:7)
    at Agent.handle [as _handle] (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:326:7)
    at DtlsClientSocket.socket.on.err (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:95:14)
    at emitOne (events.js:96:13)
    at DtlsClientSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at DtlsClientSocket.Readable.push (_stream_readable.js:130:10)
    at DtlsClientSocket._onMessage (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:89:12)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:540:8)
 This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by radzio** [comment]
This might be helpful:

https://twitter.com/home_assistant/status/925373865802502144

**Comment by treban** [comment]
Thanks for the hint. I have today same work to implement the new feature.

**Comment by radzio** [comment]
@treban  no problem and thanks for great work :)

**Comment by treban** [comment]
New version is released.
see here [pimatic-tradfri-new-version-0-1-14](https://forum.pimatic.org/topic/3781/pimatic-tradfri-new-version-0-1-14-for-new-gateway-firmware)

**Comment by matthijsf** [comment]
Thnx! Fixed it for me :-)

**Comment by cm86** [comment]
Same here!
Thx!
