### ISSUE TITLE
error after update to [tradfri 0.1.13]

### ISSUE THREAD

**Issue by cm86** [treban/pimatic-tradfri#15]
Hello,
after i update the plugin to version 0.1.13 i get the error every minute

`error [pimatic]: An uncaught exception occurred: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at OutgoingMessage.<anonymous> (/home/cm/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/tradfri-coapdtls.js:340:37)
    at emitOne (events.js:82:20)
    at OutgoingMessage.emit (events.js:169:7)
    at Agent.handle [as _handle] (/home/cm/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:326:7)
    at DtlsClientSocket.<anonymous> (/home/cm/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:95:14)
    at emitOne (events.js:77:13)
    at DtlsClientSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at DtlsClientSocket.Readable.push (_stream_readable.js:111:10)
    at DtlsClientSocket._onMessage (/home/cm/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:89:12)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)
 This is most probably a bug in pimatic or in a module, please report it!`

**Comment by treban** [comment]
i'm working on it. Update will come soon

**Comment by treban** [comment]
see here ... https://github.com/treban/pimatic-tradfri/issues/14
