### ISSUE TITLE
New update from 01-11-2017 breaks tradfri plugin

### ISSUE THREAD

**Issue by kloknibor** [treban/pimatic-tradfri#16]
Hi Since the update from 01-11-2017 which added Siri and Alexa support I can't control my tradfri devices anymore with pimatic. I get the following error : 

error [pimatic]: An uncaught exception occurred: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at OutgoingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/tradfri-coapdtls.js:340:37)
    at emitOne (events.js:82:20)
    at OutgoingMessage.emit (events.js:169:7)
    at Agent.handle [as _handle] (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:326:7)
    at DtlsClientSocket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:95:14)
    at emitOne (events.js:77:13)
    at DtlsClientSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at DtlsClientSocket.Readable.push (_stream_readable.js:111:10)
    at DtlsClientSocket._onMessage (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:89:12)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:506:8)
 This is most probably a bug in pimatic or in a module, please report it!

The release notes for tradfri where : 

Stability improvements in application connectivity to gateway

Added support for CoAP DTLS sessions

Added Gateway version in mDNS response

Use vendor specific NTP servers.

Could you please look into this? If I can help with anything let me know!

**Comment by kloknibor** [comment]
Judging by the error message we need to update tradfri-coapdtls.js : 

https://www.npmjs.com/package/tradfri-coapdtls - it's updated 22 hours ago :D

**Comment by kloknibor** [comment]
And I just noticed you are awesome and already fixed this! Sorry for bothering and thanks a lot!

**Comment by treban** [comment]
I have released yesterday a new pimatic-tradfri plugin version. 0.1.14... together with a new tradfri-coapdtls version.

Please update the plugin

**Comment by treban** [comment]
Your are welcome ;)
