### ISSUE TITLE
if a timeout occurs, pimatic crashes

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-tradfri#3]
18:17:25.544 [pimatic] error: A uncaught exception occurred: TypeError: Cannot read property 'send' of null
18:17:25.544 [pimatic] error:>    at DtlsClientSocket.dgramSocket.once.send (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:63:22)
18:17:25.544 [pimatic] error:>    at RetrySend._send (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/retry_send.js:37:14)
18:17:25.544 [pimatic] error:>    at null.RetrySend._bOff [as _onTimeout] (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/retry_send.js:29:10)
18:17:25.544 [pimatic] error:>    at Timer.listOnTimeout (timers.js:92:15)
18:17:25.544 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
18:17:25.546 [pimatic] info: exiting...

**Comment by treban** [comment]
Ok. Thanks....I will look for it.
Was the gateway reachable at this time?
And what action did you done?

**Comment by scobby** [comment]
i think the gateway wasnt reachable due to to many connetions or something else, after power off/on it was rechable again

**Comment by matthijsf** [comment]
Perhaps this relates to dit issue. After the gateway crashed pimatic gave me the following error.
```
error [pimatic]: A uncaught exception occurred: AssertionError: (not isNaN(color))
    at TradfriDimmerTemp._setColor (/root/pimatic-app/node_modules/pimatic-tradfri/tradfri.coffee:501:7)
    at TradfriDimmerTemp._setColor (/root/pimatic-app/node_modules/pimatic-tradfri/tradfri.coffee:1:1)
    at TradfriDimmerTemp.observer (/root/pimatic-app/node_modules/pimatic-tradfri/tradfri.coffee:490:12)
    at TradfriDimmerTemp.<anonymous> (/root/pimatic-app/node_modules/pimatic-tradfri/tradfri.coffee:1:1)
    at /root/pimatic-app/node_modules/pimatic-tradfri/tradfri.coffee:1:1
    at ObserveReadStream.<anonymous> (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/tradfri-coapdtls.coffee:220:15)
    at emitOne (events.js:77:13)
    at ObserveReadStream.emit (events.js:169:7)
    at readableAddChunk (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at ObserveReadStream.Readable.push (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at ObserveReadStream.append (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/observe_read_stream.js:32:10)
    at Agent.handle [as _handle] (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:298:27)
    at DtlsClientSocket.<anonymous> (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/agent.js:95:14)
    at emitOne (events.js:77:13)
    at DtlsClientSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at DtlsClientSocket.Readable.push (_stream_readable.js:111:10)
    at DtlsClientSocket._onMessage (/root/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:86:12)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)
 This is most probably a bug in pimatic or in a module, please report it!
```

`08:26:57error [pimatic-tradfri]: Tradfri gateway is not reachable anymore!`

**Comment by treban** [comment]
@matthijsf That's an other bug. It's  fixed in the next update.

**Comment by treban** [comment]
Update 0.1.11 should fix the exception errors.

**Comment by treban** [comment]
Problem Fixed: ...
https://forum.pimatic.org/topic/3075/new-pimatic-tradfri-plugin-ikea-smart-lights/46
